
exports.timelapseMenu = "Welcome to the VIEW Intervalometer!  The Time-lapse menu is the intervalometer, where you setup a simple time-lapse or automatic exposure ramp.\n To leave this help screen, press the top button on the right.  Then, press the knob or the middle button on the right to enter the Time-lapse menu.";
exports.captureMenu = "The Capture menu puts the camera into live-view mode and captures photos to the camera's memory card when the knob is pressed. Turning the knob will adjust the exposure.  Pressing the middle knob will enter focus mode, where the knob will then adjust focus if supported. \n At present, the Capture menu only works with Canon and Nikon cameras.";
exports.clipsMenu = "This is where you can playback your time-lapse clips, even while they're still recording. \n To save XMP data to an SD card while in the Time-lapse Clips menu, insert an SD card and use the bottom right button to save the XMPs for the selected clip.";
exports.settingsMenu = "Various settings including WiFi and software updates can be found here. \n  More options and settings are planned to be added soon.";
exports.wifiMenu = "Enable/disable WiFi and manage WiFi connections.  WiFi must be enabled and connected to update the VIEW software.";
exports.chargeIndicatorMenu = "Use this setting to enable or disable the charge indicator light on the left side of the VIEW, right above the micro-USB charging port.  \nIf disabled, the light will never be illuminated.  \nIf enabled (default), the light will blink while charging, remain on while connected with a full battery, and always be off if external power is not connected.";
exports.softwareMenu = "Update to the latest software for the VIEW here. You can also roll back to previous versions.  \nNote that updating to a new version can take as long as 30 minutes to complete.  Rolling back to previous versions should not take more than a minute.";
exports.wifiConnectMenu = "Use this to browse nearby access points.  Connect to an access point by selecting it and pressing the knob or the middle button on the right.  \nYou will be prompted for a password if it is a secure network.  Passwords are automatically stored and the the VIEW will attempt to connect to the previous network on the next power on. \nNote that connecting to an access point will disable the TL+VIEW local access point.";
exports.wifiEnableMenu = "This will power on and enable the WiFi interface.  Enabling WiFi decreases battery life by about 30%.";
exports.wifiDisableMenu = "This will disable and power off the WiFi interface.  Disabling WiFi increases battery life by about 30%.";
exports.wifiApMenu = "This enables the TL+VIEW access point, allowing remote control from a smartphone, tablet or computer.  It's currently not possibly to both enable the access point and connect to an outside access point, so enabling this will disconnect any other connection. \nOnce the TL+VIEW access point is enabled, connect to the access point from a web-cable device (e.g., smartphone) and open http://10.0.0.1/ in the web browser.";
exports.wifiConnect = "Pressing the knob or middle right button will connect to the selected access point and prompt for a password if needed.  Passwords are automatically stored for reconnecting.  If the TL+VIEW access point is enabled, it will be disabled before connecting to the selected access point.";
exports.softwareHelpHeader = "Pressing the knob or middle right button will install the currently selected software version.  If the version is already downloaded, it will quickly load, but new versions can take up to 30 minutes to download and install.";
exports.exposureMenu = "This puts the camera in live-view mode and allows adjusting of the exposure via the knob, or focus if the middle right button is pressed to enable the cropped view.  Press the top right button to exit. \nNote: this only works with Canon and Nikon cameras at present.  It will cause Sony cameras to crash and require a power cycle.  A fix will be released soon, but in the meantime do not use this for cameras other than Canon and Nikon.  Instead, simply setup the focus and exposure from the camera directly.";
exports.rampingOptions = "This determine the time-lapse mode: \"Basic - Fixed\" for standard time-lapse with no exposure change, or \"Auto Ramping\" for fully automatic exposure ramping.";
exports.framesOptions = "Number of frames to capture before stopping.  Switch to \"Auto Ramping\" Time-lapse Mode to have it continue until stopped.";
